language: scala
scala:
- 2.11.8
script:
- sbt clean coverage test package
after_success:
- sbt coveralls
- test "${TRAVIS_PULL_REQUEST}" = 'false' && sh "$TRAVIS_BUILD_DIR/.bintray.sh" &&
  sbt publish
env:
  global:
  - secure: JYABp0YE6s4Qk7r0aTb/rqgK41kI7btmuoKoeqaNmEqjbAkIIoFxTKfh5/3fiVjgRI1OTNu6CjmqxNpcjkeu+VbpcvKmHMzMpKwdolwG7NEyzSX7Eo2EgIuGrI/13YPQ5hsJw7iOiOw7i54cNv9iUYfII7SZ23rUPWzWujalX5M=
  - secure: kEQG2XfYJKERaF9z1KdbC5Ai3toTimTIN46FPccxzGAtWa1afr4zrvGmuiEdjffTUmtC0Uja/nkYrIKXpQ8W/ATfCRZW2OxApYB1IDGOj19HDGnOmzXj6KS0btRajC79kL56h97Web3Pinq+v8qr2pWtC75HXuz0WqywZNpQiEQ=
  - secure: Umb9F1KwDu2ftWaovYY7ptXzO0e0ZXQsVt1mZaBBrhLieyfyptRfPaisyadGh6KzelhRQqKY4nTZJtXqGJ6nuDHs9zUYemTBWsxL40MY1lI4fFWVHmEG+Y9JhKQp1YMmWUnA+0k723wuwIFtx7JpFCmZCxVN5eIAruYVYt26ksY=
  - secure: SVSNUBNAKAiQywp+k40ki+EDcgrl/bh/7FdDFzDEdmgO+0VFm1mBHEgJjtNOYLfvIrdgSBkb2xEcz5Vb2sgQD2aF3vI3+ZyR67qM6PUK7pak2v+TC+yKzGjtYXe9Z8iuA4yWAQC94rzCaFwCutKhL5DuKr7Eju0l/BwOBKffo8E=
